#!/bin/bash

START_CMD=""
KILL_CMD=""
DENY_LIST=""

if [ -n "$CMM_START_CMD" ]; then
  START_CMD="$CMM_START_CMD"
fi

if [ -n "$CMM_KILL_CMD" ]; then
  KILL_CMD="$CMM_KILL_CMD"
fi

if [ -n "$CMM_DENY_LIST" ]; then
  DENY_LIST="$CMM_DENY_LIST"
fi

DELAY="1"
ACTION=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case "$key" in
  -h|--help)
    HELP=1
    shift
    ;;
  -s|--start)
    START_CMD="$2"
    shift
    shift
    ;;
  -k|--kill)
    KILL_CMD="$2"
    shift
    shift
    ;;
  -t|--timer)
    DELAY="$2"
    shift
    shift
    ;;
  -d|--deny)
    DENY_LIST="$2"
    shift
    shift
    ;;
  *)
    ACTION="$1"
    shift
    ;;
  esac
done

if [ $HELP ]; then
  echo "Usage: $0 [-h |--help] [-s | --start <start_cmd>] [-k | --kill <kill_cmd>] -d | --deny <deny_list>] [-t | --timer <timer>] <action>"
  echo "Automatically start- or stop compositioning manager depending on a deny-list of other programs"
  echo "Where:"
  echo "  -h | --help : Print this help"
  echo "  <action>                 : one of start, stop, status, inhibit, release"
  echo "The following flags are only relevant for the 'start' action"
  echo "  -s | --start <start_cmd> : Command to start compositioning manager with"
  echo "  -k | --kill <kill_cmd>   : Command to kill compositioning manager with (defaults to pkill the first word of <start_cmd>)"
  echo "  -d | --deny <deny_list>  : Comma-separated list of programs to watch out for"
  echo "  -t | --timer <timer>     : Interval in seconds to check, defaults to 1 (once every second)"
  exit 0
fi

case "$ACTION" in
start)
  ;;
stop)
  if [ ! -d /tmp/cmm -o ! -r /tmp/cmm/pid -o ! -r /tmp/cmm/status ]; then
    echo "Not running"
  else
    kill -s INT $(cat /tmp/cmm/pid)
    exit 0
  fi
  ;;
status|inhibit|release)
  if [ ! -d /tmp/cmm -o ! -r /tmp/cmm/pid -o ! -r /tmp/cmm/status ]; then
    echo "Not running"
  else
    [ "$ACTION" == "status"  ] && cat /tmp/cmm/status
    [ "$ACTION" == "inhibit" ] && echo "1" > /tmp/cmm/inhibit
    [ "$ACTION" == "release" ] && echo "0" > /tmp/cmm/inhibit
  fi
  exit 0
  ;;
*)
  [ -z "$ACTION" ] && echo "Missing action argument" || echo "Invalid action argument $ACTION"
  exit 1
esac

CM_CMD=$(echo "$START_CMD" | cut -d ' ' -f1)

DENY_LIST=$(echo "$DENY_LIST" | sed 's/,/|/')

if [ -z "$START_CMD" ]; then
  echo "Start command not set, please set via -s flag or CMM_START_CMD environment variable"
  exit 1
fi

if [ -z "$DENY_LIST" ]; then
  echo "Deny list is empty, please set via -d flag or CMM_DENY_LIST environment variable"
  exit 1
fi

if [ -z "$STOP_CMD" ]; then
  echo "Stop command not set, assuming killall -q $CM_CMD"
  KILL_CMD="killall -q $CM_CMD"
fi

[ ! -d /tmp/cmm ] && mkdir /tmp/cmm

if [ -r /tmp/cmm/pid ]; then
  echo "cmm already running (pid $(cat /tmp/cmm/pid)? If crashed, please remove /tmp/cmm/pid and run again"
  exit 0
fi

echo "$$" > /tmp/cmm/pid
trap "rm /tmp/cmm/pid; $KILL_CMD; exit 0" INT

echo "Running, inactive" > /tmp/cmm/status
echo "0" > /tmp/cmm/inhibit

while true; do
  inhibited=$(cat /tmp/cmm/inhibit)
  cm_running=$(pgrep "$CM_CMD")
  deny_running=$(pgrep "$DENY_LIST")

  # Stop if either deny-list is active OR inhibited
  must_stop=0
  [ -n "$cm_running" -a -n "$deny_running" ] && must_stop=1
  [ -n "$cm_running" -a $inhibited -eq 1   ] && must_stop=1

  if [ $must_stop -eq 1 ]; then
    echo "[$(date +%T)] Killing CM: '$KILL_CMD'"
    echo "Running, inactive" > /tmp/cmm/status
    eval $KILL_CMD
  fi

  # Start if both deny-list is inactive AND not inhibited
  must_start=0
  [ -z "$cm_running" -a -z "$deny_running" -a $inhibited -eq 0 ] && must_start=1

  if [ $must_start -eq 1 ]; then
    echo "[$(date +%T)] Starting CM: '$START_CMD'"
    echo "Running, active" > /tmp/cmm/status
    eval $START_CMD
  fi

  sleep "$DELAY"
done
